installed_at: '2026-02-02T11:43:06+00:00'
skill_id: git/project-memory
git_repo: https://github.com/SpillwaveSolutions/project-memory
skill_path: /private/var/folders/vp/4lz1byp12z56b_btlzgr2hnw0000gn/T/skilz-git-nmyljy6c
git_sha: 7267697b6d7f960accfb4b9d6026a74a0b2fc5ff
skilz_version: 1.10.0
install_mode: copy
canonical_path: null
